[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 75"