[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
startupDelay = "90s"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5