[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 5
startupDelay = "5s"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3