[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
startupDelay = "30s"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3