[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "${HEALTH_CHECK_PATH:-/api/health}"
healthcheckTimeout = 120
startupDelay = "90s"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5