services:
  - type: web
    name: mecaflow-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: mecaflow
    region: frankfurt
    plan: free