services:
  - type: web
    name: mecaflow-backend
    env: python
    runtime: python3.11
    buildCommand: |
      # Install FreeCAD and dependencies
      apt-get update
      apt-get install -y freecad python3-pip libgl1-mesa-glx xvfb
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    startCommand: |
      Xvfb :99 -screen 0 1024x768x16 &
      uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      # Only keep non-FreeCAD related variables here
      - key: MONGO_URL
        value: mongodb+srv://islem:enpooran31@cluster0.yjykiin.mongodb.net/mecaflow
      - key: DB_NAME
        value: mecaflow
      - key: SECRET_KEY
        value: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "180"
    region: frankfurt
    plan: free
    autoDeploy: true
    healthCheckPath: /docs
